### ISSUE TITLE
Request: Have the program always open files from last location.

### ISSUE THREAD

**Issue by Lord-Quake** [bw1129/PIDtoolbox#10]
Thank you :-)

**Comment by bw1129** [comment]
I have this in mind. I realize it's a real pain wrt mac version. Maybe I'll create a button or option that saves the currently selected path as a default, or even save multiple paths which could be set up to appear in a dropdown menu of recently used paths/folders

**Comment by bw1129** [comment]
this is now fixed in the latest version 0.30, so I will close the issue.

**Comment by Lord-Quake** [comment]
Thanks Brian!
