### ISSUE TITLE
Linux build for recent versions

### ISSUE THREAD

**Issue by hickscorp** [bw1129/PIDtoolbox#100]
There was a beta release for Linux (0.55) but no subsequent support.
It would be great to have continuous builds for Linux!

**Comment by dgsardina** [comment]
+1 A Linux version of the last release will be great. Alternatively, if you could provide some insight on how  to create the Linux version maybe we can help!

**Comment by catphish** [comment]
This is marked as completed, but I don't see any releases. Is this something you're able to do for future releases? Thanks!

**Comment by bw1129** [comment]
Linux is no longer supported.

**Comment by catphish** [comment]
Thanks for confirming. That's a shame, but I got a windows VM up and running and very happy with the results.
