### ISSUE TITLE
Dosn't work on macOS 12/13 with M2pro/i5 - lastest v0.59

### ISSUE THREAD

**Issue by moorfpv** [bw1129/PIDtoolbox#102]
The App starts on my i5, macOS 12, but can not read/analyze a log file.
Infinity shown dialog: [Please wait ...]

The App dosen't start on my M2pro, macOS 13!

**Comment by Novafpv** [comment]
Check the post #93 , you will get the answer.

**Comment by moorfpv** [comment]
Thx for info-link.
Puuh, oa no, no way ... I deinstall this app again.
please build more user friendly and working apps only...
this would be very nice and helpfull for all FPV enthusiasts ...
