### ISSUE TITLE
Doesn't work on macOS Ventura 13.2.1

### ISSUE THREAD

**Issue by bobbycisneros** [bw1129/PIDtoolbox#103]
I tried with v0.58 and v0.59 and it would not start properly.  No initial help dialog box as seen on the video.

**Comment by Novafpv** [comment]
Check the post https://github.com/bw1129/PIDtoolbox/issues/93 , you will get the answer.

**Comment by bobbycisneros** [comment]
I downloaded the source and got it to work!  Thanks.  This is a temporary solution because I am running on a trial version of MatLab. What’s the plan to fix PTB for iOS Ventura? Thanks!
