### ISSUE TITLE
[v0.59] pop up windows invisible on Ventura 13.0.1

### ISSUE THREAD

**Issue by poastoast** [bw1129/PIDtoolbox#109]
I'm having an issue where the popup windows, like the initial startup help window to select the main directory, and select logs, are not working properly. If I right click the app and show all windows it also shows up as invisible. Is there any way around this or am I stuck for the time being?
To get around the main folder directory, I went into the txt file in User/Shared and manually typed in the file location, and it seemed to have worked. 
I can't use the program once the pop ups are open any time I try to load a log and I am forced to close everything.
<img width="1391" alt="Screenshot 2023-03-29 at 6 31 04 PM" src="https://user-images.githubusercontent.com/78679380/228682454-af84d9b1-bb08-4402-b716-fe9c9c2a0cd6.png">

**Comment by bw1129** [comment]
PTB does not work on ventura, yet
