### ISSUE TITLE
Highlight diffs in setup info

### ISSUE THREAD

**Issue by pulquero** [bw1129/PIDtoolbox#11]
The setup info windows displays a table comparing the bf config from two different logs. It would be nice if rows that had a difference were highlighted/emphasised in some way. This would make it easy to spot what had changed between two logs. Bolding rows with superficial differences would be something minimal that could be done, up to something comprehensive like having a third column that contains the magnitude of the difference.

**Comment by bw1129** [comment]
Good idea. The only issue would be when comparing logs from different builds as BF adds new variables in the header and this table is simply a spit out of the entire header info. Should be relatively easy to do though. I’ll put it in the pipeline of things to do. Thx
