### ISSUE TITLE
Missing "Gyro prefilt" from INAV 6.0.0 blackbox

### ISSUE THREAD

**Issue by slackista** [bw1129/PIDtoolbox#112]
Due to changes in INAV 6.0.0, raw gyro data is not showing after "Gyro prefilt" is selected.
PR for that change https://github.com/iNavFlight/inav/pull/8139

**Comment by bw1129** [comment]
Yes, I need to upgrade Ptb for inav 6. I’d be grateful for a logfile that contains prefiltered gyro so I can make changes for next version of Ptb.

**Comment by slackista** [comment]
here you go :)
https://file.io/JxZ0Cpmnt8kK

**Comment by bw1129** [comment]
@slackista you deleted the logfile. I didnt download it yet. I cant see throttle value in current INAV 6 log I have. no 4th column for set point or RC command throttle. 
can you please drop link to file again, and can you confirm whether having throttle in logfile is an option? weird it is not there by default

**Comment by bw1129** [comment]
@slackista also motor sigs not on, and rcData not on. can you turn those on. all I need is a 10 sec hover

**Comment by bw1129** [comment]
@slackista done. will be part of new release 
![image](https://user-images.githubusercontent.com/17284912/232943409-a695e55a-8085-47ec-a21e-626f41034a93.png)

**Comment by slackista** [comment]
When you expect to release new version?

**Comment by bw1129** [comment]
It’s close. Couple of weeks maybe less
