### ISSUE TITLE
Selection of multiple flights from single file

### ISSUE THREAD

**Issue by fabi9163** [bw1129/PIDtoolbox#114]
Hello @bw1129,
first: Thanks for this great software!

this time I've installed PIDtoolbox on Ubuntu like explained, works so far.
Problem: If I select a bbl-file I am not able to select multiple flights in this file like I can under Windows.
There is only a dialog in which I can input one Digit/Integer. 
Question: Is there some parsing eg. "1-4" to allow multiple selects? If not maybe you could add a "all" option on index 0.

Thanks Fabi

**Comment by fabi9163** [comment]
@bw1129 The last Linux-Version seems to be released before my issue-report on 12 April.
You closed the Issue with "completed" on 11 May.

Question: Is there a way/howto to run/compile on Linux or was this a mistake?

Thanks for your answer

**Comment by bw1129** [comment]
Sorry, no go
