### ISSUE TITLE
Can't get log files to load and be analyzed on MacOS Ventura - v0.6

### ISSUE THREAD

**Issue by chrissetty** [bw1129/PIDtoolbox#116]
I installed the new 0.6 version on my Mac running Venture and it got much, much further than before, however when I try and load a log file, it just sits there with a window that has a loading bar at about 75% and says "please wait" - no matter how long I let it sit there, it never progresses or loads any of the log files. I have placed the app folder on the Desktop, run it from there, set the Main Working Directory correctly and ensured all the log files are unlocked. Still won't load any log files.
<img width="2026" alt="Screenshot 2023-05-11 at 12 05 13 PM" src="https://github.com/bw1129/PIDtoolbox/assets/133264131/9f825d6c-1434-4c61-99cb-31e561bf7fc5">

**Comment by bw1129** [comment]
Go to ‘main’ folder and send me the ‘PTBlog’ file

**Comment by chrissetty** [comment]
Hmmmmm….this is what is in the main directory…don’t see a PTBlog file

￼

**Comment by bw1129** [comment]
if you do not know where the 'main' folder is then you did not follow the installation instructions.

**Comment by chrissetty** [comment]
Ok….Isn’t this the Main folder…that is what the name of the directory is and also where the application is, per the instructions in the readme

￼
