### ISSUE TITLE
PIDTool box not loading files 

### ISSUE THREAD

**Issue by b4tn** [bw1129/PIDtoolbox#117]
![IMG_8201](https://github.com/bw1129/PIDtoolbox/assets/47430127/a6d4337e-45ce-47e1-8f85-b9714056d2f6)

I get a dialog box that looks like it should have some buttons but nothing is clickable. The progress arrow just hangs. Using betaflight 4.4.1 and ptb .61. I tried removing all versions of ptb and maylab and doing a fresh install. Tried multiple different logs as well.

**Comment by bw1129** [comment]
Send logfile and send PTBlog.txt found in the ‘main’ folder

**Comment by b4tn** [comment]
added, thanks
[PTBlog.txt](https://github.com/bw1129/PIDtoolbox/files/11470797/PTBlog.txt)
[btfl_006.txt](https://github.com/bw1129/PIDtoolbox/files/11470798/btfl_006.txt)

**Comment by bw1129** [comment]
this means the logfile is missing some critical information. you have set logging OFF for set point and possibly other variables that are needed to run PTB. 
![image](https://github.com/bw1129/PIDtoolbox/assets/17284912/98b9c01b-2ec2-4b7f-a08c-a217c0db9338)

**Comment by bw1129** [comment]
the only fields available in the logfile are these. gyroADC is filtered gyro, plus you have debug, but no set point, no PID terms, no prefiltered gyro. 
![image](https://github.com/bw1129/PIDtoolbox/assets/17284912/6bb43cb5-644c-4c82-8659-39e2707167d3)

**Comment by bw1129** [comment]
so this is not an issue with PIDtoolbox, it is an issue with how you are logging in Betaflight. I will close this issue.

**Comment by b4tn** [comment]
It’s a new build. There are not many options in BF for log setup. It has default tune, logging rate set to 1/2 (4khz) and debug is gyro scaled. FC is a mamba MK4.

**Comment by b4tn** [comment]
If anyone stubles across this I found the issue.  In Betaflight presets there is a Gyroflow preset that reduces logging to only whats needed for processing Gyroflow video.  This preset breaks the logging function for PID toolbox.
