### ISSUE TITLE
INAV 6.1 blackbox data not loading

### ISSUE THREAD

**Issue by sdellava** [bw1129/PIDtoolbox#118]
I've downloaded the last PIDtoolbox version and tried to load data collected by a drone running INAV 6.1.

The "please wait" popup appear without any other information. The load never end.

**Comment by sdellava** [comment]
I've found no log. This is the INAV bb file that lead to the issue: 
[blackbox_log_2023-05-15_141409.zip](https://github.com/bw1129/PIDtoolbox/files/11486066/blackbox_log_2023-05-15_141409.zip)

**Comment by bw1129** [comment]
Both INAV and BF have options on what parameters to log. For both you much log set point and gyro or PTB will not run. This is done in CLI for BF. For INAV 6+ it is found in the gui. Please make sure you are logging set point, gyro, gyro raw (inav) and gyro_scaled (BF)

**Comment by bw1129** [comment]
Make sure you are logging set point. Otherwise it will crash when loading.

**Comment by bw1129** [comment]
Also if you don’t see a PTBlog.txt file you probably did not follow the read me.

**Comment by sdellava** [comment]
I've uninstalled, dowloaded again and run as stand alone. This way it works.

So I suppose the installation is not done correctly.

**Comment by bw1129** [comment]
Just tried your logfile. It works fine on my end using v0.61  
![image](https://github.com/bw1129/PIDtoolbox/assets/17284912/5cf337e0-5e40-43d4-a4f2-a4f66ae39447)

**Comment by bw1129** [comment]
this is not an issue with the software so I am closing the issue
