### ISSUE TITLE
PIDToolbox stuck in importing Betaflight logs

### ISSUE THREAD

**Issue by oblaese** [bw1129/PIDtoolbox#119]
I'm trying to load this logfile in PIDToolbox Version v0.61
[Here is my logfile](https://github.com/bw1129/PIDtoolbox/files/11524236/logfile.zip)

But it wont load the file. it shows the empty progress bar but nothing happens.

Am i missing something or is something broken?

**Comment by bw1129** [comment]
Send ‘PTBlog.txt’ file found in main folder




Sent from my iPhone

On May 21, 2023, at 7:42 AM, oblaese ***@***.***> wrote:

﻿

I'm trying to load this logfile in PIDToolbox Version v0.61
Here is my logfile<https://github.com/bw1129/PIDtoolbox/files/11524236/logfile.zip>

But it wont load the file. it shows the empty progress bar but nothing happens.

Am i missing something or is something broken?

**Comment by oblaese** [comment]
i cant find any logfiles in the Programs/PIDToolbox Directory (Windows)

**Comment by bw1129** [comment]
That’s your problem. Follow the read me

Sent from my iPhone

On May 21, 2023, at 8:10 AM, oblaese ***@***.***> wrote:

﻿

i cant find any logfiles in the Programs/PIDToolbox Directory (Windows)

**Comment by oblaese** [comment]
oohhh well. Lesson Learned. Dont ignore Readme Files again.
Thank you and sorry to bother you. :D
