### ISSUE TITLE
Not able to load bbl file

### ISSUE THREAD

**Issue by RollingGecko** [bw1129/PIDtoolbox#120]
I get an endless spinner when I try to load the log file. It is a bbl file from betaflight 4.4.1 with 2khz and scaled Gyro.

No idea what is going wrong. Tryed it on 2 computers. Both fresh installations with the latest Version of PIDtoolbox. 
[PI_0_7.zip](https://github.com/bw1129/PIDtoolbox/files/11537368/PI_0_7.zip)

**Comment by bw1129** [comment]
I tried your logfile and it works fine on v0.61, so I am closing the issue. 
![image](https://github.com/bw1129/PIDtoolbox/assets/17284912/c244b76c-76b1-4a20-ab20-26b9d40bb0a8)

**Comment by RollingGecko** [comment]
Thanks. Now I know at least, that the files are not corrupted. But I still have now I idea where the problem on my Windows System is. On Win11 and Win10.
