### ISSUE TITLE
Plot caption is behind plot settings

### ISSUE THREAD

**Issue by slackista** [bw1129/PIDtoolbox#121]
In v0.61 After generating new frequency analyzer plot, the caption field is always behind settings, which is very annoying. Changing window size doesn't help. 
![image](https://github.com/bw1129/PIDtoolbox/assets/20584264/dd91e19a-2583-4a25-91b7-e9959dc55ebc)

**Comment by bw1129** [comment]
fixed in v0.62. closing issue
