### ISSUE TITLE
pidtoolbox not opening up logs, need steps on how to set up blackbox to log the correct way

### ISSUE THREAD

**Issue by GarminCookie** [bw1129/PIDtoolbox#123]
just sits at please wait loading window forever

**Comment by bw1129** [comment]
Please send the logfile and the ‘PTBlog.txt’ file found in main folder

**Comment by Combinacijus** [comment]
@GarminCookie How did you solve it. I have the same problem?

**Comment by Combinacijus** [comment]
Nevermind, I had to launch PIDtoolbox from the folder I DOWNLOADED from github (and not the that that got installed). Found it here #119. Everything was in README_PLEASE.txt but I missed it
