### ISSUE TITLE
How to solve dpi/font scaling issues on Windows

### ISSUE THREAD

**Issue by marianomd** [bw1129/PIDtoolbox#124]
Is there an easy way to solve this? I tried the Windows compatibility options but apart from font smoothing I couldn't get the text to fit.

![image](https://github.com/bw1129/PIDtoolbox/assets/274989/6b046cb2-d1ef-4d0a-a5b6-23d4176ec738)

Thanks for the great tool.

**Comment by bw1129** [comment]
Ah font size not being applied to that. Bug fix coming


Sent from my iPhone

On Jul 26, 2023, at 12:24 PM, Mariano Dupont ***@***.***> wrote:

﻿

Is there an easy way to solve this? I tried the Windows compatibility options but apart from font smoothing I couldn't get the text to fit.

[image]<https://user-images.githubusercontent.com/274989/256299369-6b046cb2-d1ef-4d0a-a5b6-23d4176ec738.png>

Thanks for the great tool.

**Comment by marianomd** [comment]
Thanks Brian!
