### ISSUE TITLE
MacOS - can't change current folder (name nonexistent)

### ISSUE THREAD

**Issue by vaska1992** [bw1129/PIDtoolbox#127]
I followed the guide to set the current folder to one on my desktop, but PTB was in a subfolder on my desktop and apparently i had spaces in the folder name, and it seems to hate that, on the error message it shows my folder name without spaces, so i figured it doesnt like it and i cannot change it to choose another one, the application closes as soon as i click "ok" on the error message. 
How can i clean it up and do fresh install?

**Comment by bw1129** [comment]
go to 'users/shared' and remove all txt files named 'mainDir-PTBv...' then try again
________________________________
From: vaska1992 ***@***.***>
Sent: Tuesday, October 10, 2023 9:50 AM
To: bw1129/PIDtoolbox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bw1129/PIDtoolbox] MacOS - can't change current folder (name nonexistent) (Issue #127)


I followed the guide to set the current folder to one on my desktop, but PTB was in a subfolder on my desktop and apparently i had spaces in the folder name, and it seems to hate that, on the error message it shows my folder name without spaces, so i figured it doesnt like it and i cannot change it to choose another one, the application closes as soon as i click "ok" on the error message.
How can i clean it up and do fresh install?

**Comment by vaska1992** [comment]
Thanks! that did it. 
moral of the story: don't use spaces in folder path names :)
