### ISSUE TITLE
Mac Os X install

### ISSUE THREAD

**Issue by orlovskiy** [bw1129/PIDtoolbox#17]
Mac os X 10.13.6 
I've got some errors during install which is:
![Снимок экрана 2019-06-05 в 2 08 14](https://user-images.githubusercontent.com/16646994/58920336-5119a980-873a-11e9-926d-7b649f1d9cc9.png)
And another one kinda like this. After those two I got "Installation successfull" message. After finished installation there is an empty folder PIDToolbox in Applications. When I run the program from Downloads folder(or copying contents of "main" folder to created empty folder in Applications) it is stocking on 
![Снимок экрана 2019-06-05 в 2 31 52](https://user-images.githubusercontent.com/16646994/58920363-83c3a200-873a-11e9-9e61-8901f9f63a50.png)
Also I have installed MATLAB Runtine R2018b downloaded from MATLAB's site. 
Completely stocked, but very interested in trying this.

**Comment by exocode** [comment]
Only wanna join, have the same issue:

```
Source '/private/var/folders/k9/kt8cnmqj5h10wvh142d8znv40000gn/T/AppTranslocation/8D3E9C1A-55FB-41B8-BF8D-816508C109B8/d/MyAppInstaller_web.app/Contents/Resources/bundle.zip' does not exist
```

When installation wsa finished I saw this:

```

Product Configuration Notes:  In the following directions, replace MR/v95 by the directory on the target machine where MATLAB is installed, or MR by the directory where the MATLAB Runtime is installed.  If the environment variable DYLD_LIBRARY_PATH is undefined, set it to the following string:  MR/v95/runtime/maci64:MR/v95/sys/os/maci64:MR/v95/bin/maci64  If it is defined, set it to the following:  ${DYLD_LIBRARY_PATH}:MR/v95/runtime/maci64:MR/v95/sys/os/maci64:MR/v95/bin/maci64 
```

**Comment by exocode** [comment]
If I load any file on my MAC I get this after pressing "load + run". Why is it calling for an .exe file? Mac users cant open exe files without installing additional programs.

<img width="446" alt="Bildschirmfoto 2019-06-19 um 06 13 21" src="https://user-images.githubusercontent.com/1597621/59736354-8c979600-9259-11e9-9b12-3fb3f95e1df1.png">

**Comment by bw1129** [comment]
@exocode it's a generic error label, but it's fixed in later version. Ignoring the .exe part, the message is still valid. it does not see blackbox_decode in same folder as log files you selected. try placing the log files in same folder as those program files (the mac versions of bb decode and pidtoolbox) then select the log file from that folder

**Comment by krzysztofmatula** [comment]
Hi,
How do you pass over the "File '/private/var/folders/4t/9071clns5nlbxnqwzz04hyfc0000gn/T/AppTranslocation/6D0C468D-5FA9-455E-941F-F846822B65B7/d/MyAppInstaller_web.app/Contents/Resources/bundle.zip' does not existthe " message?

I'm trying the latest PIDtoolbox release and I'm getting exactly the same as in this issue description...

Is there some workaround?

**Comment by krzysztofmatula** [comment]
Answering my own question: this helps:
```sudo xattr -d com.apple.quarantine MyAppInstaller_web.app```
