### ISSUE TITLE
PIDToolbox cant read BF 4.04

### ISSUE THREAD

**Issue by jasc76** [bw1129/PIDtoolbox#18]
Hi

I tried to analyse a BF4.04 Log 
Name/Version: 4.0.4
Binär: betaflight_4.0.4_MAMBAF722.hex
Datum: 01-07-2019 14:36

The csv is created and PTB reads it and the progress bar disappears but then PTB just hangs
Tried a older Log on the same computer and works fine

Regards
Jan

**Comment by bw1129** [comment]
Can u upload the logfile so I can take a look?

**Comment by jasc76** [comment]
here it is
FC is mamba 722 mini
frame: Diatone Exorcist
sadly no Gyro scaled...forgot :-)
PIDs / Filters all BF 4.0.4 stock
Motors Flywoo 2207
[btfl_002.zip](https://github.com/bw1129/PIDtoolbox/files/3365592/btfl_002.zip)

**Comment by bw1129** [comment]
I have no issue opening on v0.23. What version are you using? 

![Screen Shot 2019-07-07 at 11 02 49 AM](https://user-images.githubusercontent.com/17284912/60770230-cadce400-a0a6-11e9-9301-9281e808ff2f.png)

**Comment by jasc76** [comment]
yes 0.23
 
Did you try session 2 ?

![grafik](https://user-images.githubusercontent.com/42022027/60770513-b23af100-a0db-11e9-8eda-9acd30ca1e1b.png)
I hear the windows "bing" sound and progress bar shows 100% (see picture)

**Comment by bw1129** [comment]
yes. Log 1 top, log 2 bottom. 

![Screen Shot 2019-07-07 at 12 37 19 PM](https://user-images.githubusercontent.com/17284912/60771307-1944af80-a0b4-11e9-8cb3-c750fe15f56b.png)

**Comment by bw1129** [comment]
try grabbing the latest exe again from 
https://github.com/bw1129/PIDtoolbox/releases
You dont have to download runtime again, just grab PIDtoolbox.exe and replace yours with this one.

**Comment by jasc76** [comment]
Did that, doesnt help. After selecting the session PTB works (cpu+ram) when Progress bar is at 100% I get the windows notification sound, cpu+ram drops to 0 but nothing else happens

**Comment by jasc76** [comment]
Other logs work, also session 1

**Comment by bw1129** [comment]
it's working on 0.23 on both my Windows and Mac machines. Not sure what to say, but there's nothing I can do on my end if all is aok here, and I've not heard other reports of any issues. 0.30 will be released in the coming weeks so maybe give that a try, and hopefully that works for ya. that's about all I can say at this point.

**Comment by jasc76** [comment]
Thanks for your effort! 
Then, I guess, my Computer has an issue...

**Comment by m013** [comment]
the same problem for me. stucks at converting (progress bar instantly goes 1/3 and nothing)
on both my mac and windows pcs

version 0.23

**Comment by bw1129** [comment]
@m013
Can you upload the log file? I’ll take a look.

**Comment by m013** [comment]
@bw1129  , sure.


[main.zip](https://github.com/bw1129/PIDtoolbox/files/3401586/main.zip)

**Comment by bw1129** [comment]
@m013, ah ha. I've had this happen to me before. for some reason blackbox records a whole bunch of dud log files woth no information, amongst the few real log files that are near the end. the problem arises when blackbox_decode.exe (part of BB tools) only extracts up to the first ~30 logs and will not convert numbers higher than this. Im not sure quite why, but I have to ask about this potential issue to the developers of blackbox_decode.exe, and/or why blackbox records these junk files. This might be a new issue for betaflight. I will look into it. I should mention, I had the same problem on earlier versions of BF. I have a hunch that onboard logging devices add an empty log file to the onboard flash every time the copter is plugged in, and unless a log recording is selected, it just leaves the empty log on there. blackbox_decode.exe might be just programmed to ignore anymore than ~30 logfiles, presuming that this would not be possible memorywise. anyway, let me look into it. 
![image](https://user-images.githubusercontent.com/17284912/61391180-27e84f00-a88a-11e9-9a43-3a3167305534.png)

**Comment by m013** [comment]
I have been getting this crap data since forever on fcs with onboard memory chips. Bb explorer and plasmatree pid analyzer recognize it correctly tho

**Comment by ijustwannafly** [comment]
This is now happening to me on certain log files.

Bf 4.0.4.  Pidtoolbox v0.31.  

Blackbox explorer can open and read the log file fine but pidtoolbox just hangs with no progression.  Other files are no issues.


[2.zip](https://github.com/bw1129/PIDtoolbox/files/3539195/2.zip)

**Comment by bw1129** [comment]
@ijustwannafly  check my comment above. open in BBE, look to see if more than 30 files in drop down. if so, tis is the issue. I am still working on it, but bb_decode sets limit on # of logs to extract in a file. BF create a new blank file each time FC is enabled. only solution for this issue right now is to ensure you logging flash drive is cleared before collecting new logs.
