### ISSUE TITLE
Feature Request: Add D-Min value to PIDF

### ISSUE THREAD

**Issue by TimCiarlette** [bw1129/PIDtoolbox#26]
First off: Thank you for the Awesome PIDToolBox software, just love it.
My request is to add the D-Min value to the "Step Response Tool" for the Roll, Pitch, and Yaw.
You can add it to "PIDF:" to make it "PIDFM:", I think it would be a great addition to this software.

**Comment by bw1129** [comment]
Great idea! Will do.


Sent from my iPhone

On Oct 3, 2019, at 9:10 PM, TimCiarlette <notifications@github.com<mailto:notifications@github.com>> wrote:


First off: Thank you for the Awesome PIDToolBox software, just love it.
My request is to add the D-Min value to the "Step Response Tool" for the Roll, Pitch, and Yaw.
You can add it to "PIDF:" to make it "PIDFM:", I think it would be a great addition to this software.

**Comment by TimCiarlette** [comment]
Thank you very much, works great.
