### ISSUE TITLE
Fails to load file...

### ISSUE THREAD

**Issue by kmitchel** [bw1129/PIDtoolbox#3]
My BB logs will not open...a dong sound plays, and the progress bar freezes.

https://www.dropbox.com/s/f6nkctkybrz2npq/BTFL_BLACKBOX_LOG_iCr4sh_20190205_180121.BBL%20%282%29.csv?dl=0

**Comment by bw1129** [comment]
make sure the csv was created from bloacbox explorer. it will not run csv files created from blackbox_decode. second thing to try, place csv in folder with PIDtoolbox.exe.

**Comment by kmitchel** [comment]
Moving the csv files into the same directory as the executable has helped. I still have one file that still freezes.  I'll continue to try others.  Should it still load with the wrong debug mode? TY

**Comment by bw1129** [comment]
It should be fine now. Just make sure the csv was generated in explorer. That’s critical. Make sure debug set to gyro_scaled, though it should run fine with any debug mode, but PIDtoolbox expects debug variables to contain unfiltered gyro.

**Comment by DusKing1** [comment]
I now have the same issue. Two csv files was exported by blackbox explorer, and they are in same folder with .m files. The CMD in matlab said:

> 出错 PTprocess (line 126)
> dat_B=dataB.DataMain(Time_B>ttb(find(ttb>y(1),1)) & Time_B<ttb(find(ttb>y(2),1)),:);
> 计算 UIControl Callback 时出错。

 (I'm using Chinese, and don't know how to change the language. Sorry for the mess)

**Comment by DusKing1** [comment]
OK, after restarting my computer some problem gone. But still got same frozen situation as kmitchel.

**Comment by bw1129** [comment]
Try putting csv in folder with PIDtoolbox.exe.

**Comment by kmitchel** [comment]
Seems to have helped.  TY.

**Comment by kmitchel** [comment]
I usually use a version of BBE built off of the latest master branch commits...this seems to contribute to my loading problems.

**Comment by bw1129** [comment]
The next version you can open bbl/bfl files directly. Also working on path related issues so this should all work better.
