### ISSUE TITLE
open file B error in PTprocess

### ISSUE THREAD

**Issue by filippov-shurik** [bw1129/PIDtoolbox#32]
Error opening file b and does not display a graph B
Screenshot 
[ps1](https://drive.google.com/file/d/1ibJPTHxIucI4bfmeoUXh1RjLJVvhc_od/view?usp=sharing)
[ps2](https://drive.google.com/file/d/14yVBX6xGZcYWWHDoWqxcdvv3xpFITasF/view?usp=sharing)

**Comment by bw1129** [comment]
What version of Ptb? Did you try a different file?

**Comment by filippov-shurik** [comment]
version 0.39

**Comment by bw1129** [comment]
Did you try another logfile to rule out the possibility that it is an issue with that logfile?

**Comment by bw1129** [comment]
I think this is now addressed in the update for v0.39, so I will close this issue
