### ISSUE TITLE
Step Response graphs incorrect at 500hz (OpenLog via UART)

### ISSUE THREAD

**Issue by grahamcropley** [bw1129/PIDtoolbox#35]
Using an OpenLog SD module via a hardware UART on a Mamba F411AIO Toothpick FC.

UART set to 250000 will only log up to 500hz (Samsung Evo 32Gb HC U1)

My rates are ~1000dps, if I do full deflection flips and rolls, it says insufficient data, and no lines are shown on the step response graph for pitch/roll with default (40-500dps)... Seems to show yaw ok.

If I up the 'degrees per second' to 2000 then it shows the familiar graph (N=30+ as expected)... it's as if it's not interpreting the lower logging rate correctly, and range needs to be doubled/tripled to be included.

Blackbox Explorer loads the data correctly. But PIDToolbox's Step Response is essential!!!

**Comment by grahamcropley** [comment]
![image](https://user-images.githubusercontent.com/17528719/73982530-5748d100-492c-11ea-8747-729c10e281f2.png)
![image](https://user-images.githubusercontent.com/17528719/73982549-5dd74880-492c-11ea-93b4-c63c943ea3cd.png)
![image](https://user-images.githubusercontent.com/17528719/73982595-70ea1880-492c-11ea-87e8-467d3d5d7fcc.png)

Example log:
[LOG00011.BBL.TXT](https://github.com/bw1129/PIDtoolbox/files/4167922/LOG00011.BBL.TXT)

**Comment by bw1129** [comment]
Dang, I never expected anyone to log at 500hz. It won’t work. It’ll take some mucking around to make Ptb deal with those. I know, that’s bad programming. Sorry bout that. Is it not possible to log at least @1k?

**Comment by grahamcropley** [comment]
Nah, it seems to get corrupted on anything higher than 1khz.. it sucks.
When loading it, it only shows <0.5 seconds if it reads it at all. iirc it says something like dimensions don't match.. or must match etc.

Maybe I need to buy one of the newer I2C / SPI based loggers instead of UART.. or I should have got a FC with blackbox.. haha. - Thanks for the reply man.

**Comment by bw1129** [comment]
Ah I see. Sorry bout that.

**Comment by bw1129** [comment]
If you have a 1k logfile drop me a
Link. I might be able to solve that issue.

**Comment by grahamcropley** [comment]
I didn't keep any from previous testing, but I'll hook it up again tomorrow and get one for you.. thanks!

**Comment by grahamcropley** [comment]
Here's a 1khz blackbox log file. No fancy flying, just hovering for ~30-40 seconds.
[LOG00018.BBL.TXT](https://github.com/bw1129/PIDtoolbox/files/4172529/LOG00018.BBL.TXT)

Seems pretty unusable in anything... I think it just can't handle it.

Blackbox Explorer only seems to show the first 200 samples. 
![image](https://user-images.githubusercontent.com/17528719/74057848-af3f1080-49dc-11ea-9646-7f46d77a6d85.png)

PIDToolBox error is 'Matrix dimensions must agree'.
![image](https://user-images.githubusercontent.com/17528719/74057863-b5cd8800-49dc-11ea-8c65-e1b16f230867.png)

Blackbox_decode output is...
![image](https://user-images.githubusercontent.com/17528719/74058035-11981100-49dd-11ea-87ac-041d4a986646.png)

**Comment by bw1129** [comment]
it actually does not contain data. here is the log in BBE. there's nothing in it. that's likely an issue with the logger 
![image](https://user-images.githubusercontent.com/17284912/74059317-cb7b8700-49b5-11ea-9aae-5a0569e48be6.png)

**Comment by grahamcropley** [comment]
There's ~900Kb of something, but yeah I'm seeing the same, and I agree, likely all totally corrupt beyond the first buffer length... i.e. maybe too much data trying to be pushed over the baud-rate of the port.. or too much for the openlog chip itself to buffer and write to SD.

If anything it would be in blackbox_decode to see if it could skip incomplete records and look for next start of row flag (if there is one, not looked at the BBL file format).

Thanks for looking anyway, I think I can get what I need by just changing the dps up to 2000 or more.

Cheers dude

**Comment by bw1129** [comment]
Ya a few bytes are used to generate header and such. But there’s no real data in there.

**Comment by JoeriCapens** [comment]
Hi @grahamcropley , you may want to try setting your uart to 500000 baud by using the command line, see my comments here: https://github.com/betaflight/betaflight-configurator/commit/74445a4b4b62e3f86ebb5bc4cc37f903149d22d3

**Comment by grahamcropley** [comment]
@JoeriCapens thank you!!.. sorry for the late response, but I just wanted to follow up and say it worked.. Thanks for commenting... it's much appreciated. (y)
