### ISSUE TITLE
Mirrored graph data in windows 10 virtual machine

### ISSUE THREAD

**Issue by jimmybe123** [bw1129/PIDtoolbox#36]
just having an issue running pidtoolbox on my Linux system running a windows 10 virtual machine on virtualbox. All the buttons etc are fine but any graph data is both upside down and reversed.  Im trying to avoid doing a bare metal windows install as the only thing I want it for is pidtoolbox lol.

**Comment by jimmybe123** [comment]
![image](https://user-images.githubusercontent.com/58280058/74496930-b31ce680-4f38-11ea-8669-ea09eb09c8c8.png)

**Comment by bw1129** [comment]
That’s the most bizarre thing I’ve ever seen. Nothing I can do on my end. It’s like a weird OpenGL issue, but nothing to do with pidtoolbox. Sorry bout that.

Sent from my iPhone

On Feb 13, 2020, at 9:46 PM, jimmybe123 <notifications@github.com> wrote:

﻿

[image]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F58280058%2F74496930-b31ce680-4f38-11ea-8669-ea09eb09c8c8.png&data=02%7C01%7Cbrian.white%40queensu.ca%7C549bfee0b03b421d7be408d7b0f81a3e%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637172451966295838&sdata=Ta2k2K9i3eD8Tq08dXduDg0IT5WxPi41roXfX7ak0uY%3D&reserved=0>

**Comment by jimmybe123** [comment]
> That’s the most bizarre thing I’ve ever seen. Nothing I can do on my end. It’s like a weird OpenGL issue, but nothing to do with pidtoolbox. Sorry bout that.
> […](#)
> Sent from my iPhone On Feb 13, 2020, at 9:46 PM, jimmybe123 <notifications@github.com> wrote: ﻿ [image]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F58280058%2F74496930-b31ce680-4f38-11ea-8669-ea09eb09c8c8.png&data=02%7C01%7Cbrian.white%40queensu.ca%7C549bfee0b03b421d7be408d7b0f81a3e%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637172451966295838&sdata=Ta2k2K9i3eD8Tq08dXduDg0IT5WxPi41roXfX7ak0uY%3D&reserved=0> — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbw1129%2FPIDtoolbox%2Fissues%2F36%3Femail_source%3Dnotifications%26email_token%3DAED36MEOXYM3PMFO7W6VSY3RCYAYRA5CNFSM4KU6XPOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELXL33A%23issuecomment-586071532&data=02%7C01%7Cbrian.white%40queensu.ca%7C549bfee0b03b421d7be408d7b0f81a3e%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637172451966295838&sdata=P%2Fj9%2Bcrjnr5uRb7CFEITiD0BYGT0KTarg83G%2FWtR%2Be4%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAED36MH533KANXR6MXAGB5LRCYAYRANCNFSM4KU6XPOA&data=02%7C01%7Cbrian.white%40queensu.ca%7C549bfee0b03b421d7be408d7b0f81a3e%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C637172451966305833&sdata=m0%2FKn%2BvsnMi3hwES4wP9i3wSs6Vqw4KKbMF8LSbr3Jk%3D&reserved=0>.

No problem, if anyone else faces this issue I solved it by using VBoxVGA and disabling 3D acceleration in the virtualbox display settings. Thanks for a great piece of software.
