### ISSUE TITLE
Hardware LPF delay is calculated incorrectly.

### ISSUE THREAD

**Issue by DusKing1** [bw1129/PIDtoolbox#37]
The method you use in `PTspecUIcontrol.m` to calculate(if I can say so) the delay of hardware digital LPF is incorrect. See in:
https://github.com/bw1129/PIDtoolbox/blob/5a83abf104ba9099cf2875f1a97265cb2f453fc0/PTspecUIcontrol.m#L246

What I mean is, **not all gyro's DLPF is 250hz.** 

For example, Bosch's BMI160 which is used by BrainFPV is running at 3200hz ODR(output data rate), By consulting the datasheet, the **cutoff is 890hz.**

I noticed this detail by re-watching UAVtech's [Bosch vs. TDK Gyro Comp video](https://youtu.be/wZM0z1Yz_6w). Though I think it is not a real big issue, it might cause some unnecessary misunderstanding, at least a pro racer asked me about this and it confused me for some time.

**Comment by bw1129** [comment]
yes you are right. In the next version, I will get rid of that altogether because it doesn't matter

**Comment by DusKing1** [comment]
Cool!
