### ISSUE TITLE
How about create more wikis for users

### ISSUE THREAD

**Issue by DusKing1** [bw1129/PIDtoolbox#4]
This project is interesting! I think if there could be more wiki pages just like plasmatree's pid-analyzer.

**Comment by bw1129** [comment]
Will do. It’s in the pipeline. Also working on a video. Thx

**Comment by bw1129** [comment]
> This project is interesting! I think if there could be more wiki pages just like plasmatree's pid-analyzer.

**Comment by bw1129** [comment]
A detailed wiki has been created

**Comment by DusKing1** [comment]
Awesome! And plz add more real world examples. If you need I can record the bblog that you requires.

**Comment by bw1129** [comment]
Absolutely! If you have some really interesting logs and comparisons, post them to the Facebook log review site and I could include em in the wiki.

Sent from my iPhone

On Mar 31, 2019, at 10:14 AM, DusKing1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome! And plz add more real world examples. If you need I can record the bblog that you requires.
