### ISSUE TITLE
Error in PTload - Invalid file identifier. Use fopen to generate a valid file identifier

### ISSUE THREAD

**Issue by jasc76** [bw1129/PIDtoolbox#40]
Hi

I get this error. Already did a reinstallation. 
BF4.1 Log
https://1drv.ms/u/s!AqdVRzkS_NXbg-cmh335qhfCOOEcRQ?e=hhRHQi

**Comment by bw1129** [comment]
no issue with loading it here. Make sure blackbox_decode is in the same folder as that logfile.

![slim_20200412_2_btfl_002-1](https://user-images.githubusercontent.com/17284912/79071737-49585900-7cab-11ea-8dac-006d6c90d83f.png)

**Comment by jasc76** [comment]
it is in the folder of the log .... :-(
I tried deinstalling pidt and mathlab but didtn help 

![grafik](https://user-images.githubusercontent.com/42022027/79073793-c48c3000-7ce8-11ea-8b44-f72aa4acc549.png)

**Comment by bw1129** [comment]
Do you have any logfiles that work? If so, put this logfile in the location of the working logfiles. Double confirm that there are other working logfiles in that folder. This is definitely a directory issue. Are you using v0.39?

**Comment by bw1129** [comment]
If all that still fails put the logfile and bbdecode in the same folder as Ptb executable.

**Comment by jasc76** [comment]
no, i wont load any log
trying blackbox_decode from cmd works fine

![grafik](https://user-images.githubusercontent.com/42022027/79074072-a1628000-7cea-11ea-800d-e02408120a7c.png)

putting both (bb log and bb decode) in the ptb application folder results in the same error

**Comment by bw1129** [comment]
Has it ever worked? If not, I’d reinstall. Make sure you use the supplied installer. Don’t go to the matlab site yourself and download runtime. In most cases that won’t work. Use the supplied installer. Btw, is this windows or Mac?

**Comment by jasc76** [comment]
yes it worked some time ago

I deinstalled ptb and matlab, afterwards deleted all folders under program files and reinstalled with the ptb installer (including new matlab download)

its windows

**Comment by jasc76** [comment]
Its kinda funny
if I run it from the installation folder I get the error

If I run it from the download folder, it works

I copied everything from the donwload over to the programfiles application folder and it doesnt work

**Comment by bw1129** [comment]
Ok, so problem solved. Yea I should have mentioned, leave everything where it is and work from there. You should be able to put that entire download folder somewhere else as long as you leave everything in place. Just use a shortcut to the executable if you want a startup icon in your desktop. Just to confirm you’re using a mac right?

**Comment by jasc76** [comment]
Its windows...
Solved, well, kind of. It doesnt work if I run it from the installation directory: C:\Program Files\PIDtoolbox\application
It works if I run it from here: C:\Users\jansc\OneDrive\Quadcopter\tools\PIDtoolbox\PIDtoolbox_v0.39_win\PIDtoolbox_v0.39_win\main

it even does not work if I copy everything from the working folder to the folder in ProgramFiles

**Comment by bw1129** [comment]
the only thing installed is runtime. The pid toolbox executable is kinda independent. But it should work pretty much anywhere else on your main C drive. It might have something to do with user rights within certain folders. Not sure. Also it’s worth noting there’s a little txt file that reads the previous log location. It’s possible this is messing with the directory if you have another copy of that somewhere. Try looking for that file in other locations of your computer. It would have been created in the selected folders only

**Comment by ai91** [comment]
Confirming - getting same issue when installed in **Program Files**.
Problem seems to be in necessaty to create **logfileDir.txt** file.
Workarounds:
1. move PIDtoolbox to not protected path
2. start as admin
3. modify access permission on **Program Files\PIDtoolbox\application** - grant full access to all users

**Comment by Topher84** [comment]
> Confirming - getting same issue when installed in **Program Files**.
> Problem seems to be in necessaty to create **logfileDir.txt** and intermediate ***.csv** files.
> Workarounds:
> 
> 1. move PIDtoolbox to not protected path
> 2. start as admin
> 3. modify access permission on **Program Files\PIDtoolbox\application** - grant full access to all users

Can confirm that right-clicking and running as admin fixes it for me. I did not have to do anything else. I used the installer to install the most recent release and had the same issue.

**Comment by bw1129** [comment]
Thx for the info. Please leave this here for others that may experience similar issue.
