### ISSUE TITLE
Problem when loading different logs with same filenames

### ISSUE THREAD

**Issue by ai91** [bw1129/PIDtoolbox#41]
When loading two .bbl files with same file name, the tool ignores one of the file, and loads second file twice.
Steps to reproduce:

1. Load **A** log file .bbl from **Path1\btfl_001.bbl**
2. Load **B** log file .bbl from **Path2\btfl_001.bbl**

Result: both **A** and **B** are filled with **B** log.

3. Start any tool (e.g. **Step Resp Tool**)

Result: outputs for **A** and **B** are identical

Problem seems to be caused by import-procedure: files get conveted into .csv-files in application folder. As result getting .csv-files collision.

Workaround:
Before import, rename files.

**Comment by bw1129** [comment]
Place all logfiles in same folder, always. Rename them if they have same name. Make sure blackbox_decode is in that folder with the logfiles.
