### ISSUE TITLE
Can not load log file (maybe same as #43)

### ISSUE THREAD

**Issue by mrRobot62** [bw1129/PIDtoolbox#45]
[btfl_001.bbl.zip](https://github.com/bw1129/PIDtoolbox/files/4812456/btfl_001.bbl.zip)

Hi,
I use latest BF 4.1 FW on my copter, running under MACOSX. Few minutes ago I made a short flight and tried to load log file into Ptb - unfortunately with some error messages during loading.

<img width="417" alt="Ptb_error2" src="https://user-images.githubusercontent.com/949032/85272582-a70fdb00-b47c-11ea-94a0-40f5e88052c2.png">
<img width="417" alt="Ptb_error1" src="https://user-images.githubusercontent.com/949032/85272591-a9723500-b47c-11ea-8b06-07f1cf89d77b.png">

As attachment my bbl file too.

With BB-Explorer it's possible to load this file.

Any suggestions?
Thanks in advance , Bernd

**Comment by bw1129** [comment]
Sure, drop the logfile here and I’ll take a look.

**Comment by mrRobot62** [comment]
Hi brain, thanks fortgesponnenes.log should attaches in my thread - isn’t it? 🤔

Viele Grüße
Bernd

Von meinem iPhone gesendet

**Comment by mrRobot62** [comment]
Any news, why I can‘t load my logfile into PIDtoolbox?

**Comment by bw1129** [comment]
Quick question, have you recently upgraded from a previously working version?

**Comment by bw1129** [comment]
@mrRobot62 I have no issue opening your logfile here. Make sure you select logfile 2 in there. logfile 1 is <2sec long. 99% of the time the reason people can not open a logfile is because of a directory issue. Make sure blackbox_decode is in the same folder as the logfile. Because BF makes logfiles the same name it's easy to get confused here, sometimes grabbing what looks like the correct logfile, or else Ptb gets confused as to which directory it's supposed to look, based on a pre-existing version of Ptb with another "main" folder with bb decode and more importantly the logfiledir.txt file causing Ptb to look in the wrong place. I always recommend putting all logfiles in the same place in the main folder with Ptb and bb decode, and just renaming the logfiles to avoid duplicates. also, when upgrading Ptb, just grab the new Ptb app/exe and replace the old one with it, in the same folder. Let me know if any of this helps.

**Comment by mrRobot62** [comment]
Hi Brain, thanks for response. Problem solved. You're right, blackbox_decode (on MACOSX too) must be available in the same folder as the log file(s).

PTB Application can be located at any place on the harddiks. Normally every applications will be installed under /Application folder on a MAC and that works.

Problem is blackbox_decode, this 90k little file must be in the same folder as the log file :-)

Brain, maybe I'm wrong, but if I take a look into PTImport.m, you call via system-call blackbox_decode on row 41 with parameter filename. Do this filename contain the file path too?

If not, maybe it's possible to include file path + file name and set it as parameter to the decode. If this work, than the decode-app can be located "anywhere"

Maybe it'S a good solution to work every time with absolute path & filenames and not a "change dir" into a "working folder".

**Comment by bw1129** [comment]
The reason bb decode has to be in same folder is not just for it’s own sake but it generates a csv file and better to have that located in same folder as the bbl for extracting data and working with. I wouldn’t want to deal with csv data being in one place and the logfile in another place.

**Comment by mrRobot62** [comment]
ah - ok - I was wondering "who" create this tmp folder with a CSV file inside - so it's bb_decode. Ah - ok.

BTW: I know (a little bit) MatLab. What do I need to compile your code and build an executable package? I assume it's the compiler-package from them, isn't it? Is to compiler package in the HOME-Edition included?

**Comment by bw1129** [comment]
If you have Matlab you can run the scripts out of the command window. But you will need a bunch of toolboxes and they’re costly unless you’re affiliated with a university of something.

**Comment by mrRobot62** [comment]
unfortunately not :-( - but maybe via my daughter she studies in Berlin. I close this issue, because it's solved

**Comment by mrRobot62** [comment]
Hi Brian,

Unfortunately I have no longer connections to university.

BTW:
What do you think, make it sense to have a German wiki pages for PID-Toolbox on Git?
If yes, I can try to start with a translation. One big advantage is, I will learn a lot ;-)

Regards
Bernd

Von meinem iPad gesendet

**Comment by bw1129** [comment]
Sure, if you’re u for the challenge.

**Comment by bw1129** [comment]
One minor issue is the wiki is pretty dated. The basics should still apply though I suppose

**Comment by mrRobot62** [comment]
Hi, ah ok, mhm, first step I start with a translation and afterwards we (you) include more and more updates.

 

Question is, how, we can choose languages - via link or is there an other solution on git? Not sure, mhm...

 

Gesendet: Dienstag, 30. Juni 2020 um 21:23 Uhr
Von: "Brian White" <notifications@github.com>
An: "bw1129/PIDtoolbox" <PIDtoolbox@noreply.github.com>
Cc: "Bernd Klein" <berndklein@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [bw1129/PIDtoolbox] Can not load log file (maybe same as #43) (#45)


 
One minor issue is the wiki is pretty dated. The basics should still apply though I suppose

**Comment by mrRobot62** [comment]
Because my idea is to work with different sites and not one big monster ;-) - like today.

 

I will think about it .....


Gesendet: Dienstag, 30. Juni 2020 um 21:23 Uhr
Von: "Brian White" <notifications@github.com>
An: "bw1129/PIDtoolbox" <PIDtoolbox@noreply.github.com>
Cc: "Bernd Klein" <berndklein@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [bw1129/PIDtoolbox] Can not load log file (maybe same as #43) (#45)


 
One minor issue is the wiki is pretty dated. The basics should still apply though I suppose

**Comment by mrRobot62** [comment]
I see, I have no access rights to update the wiki

 
 

Gesendet: Dienstag, 30. Juni 2020 um 21:23 Uhr
Von: "Brian White" <notifications@github.com>
An: "bw1129/PIDtoolbox" <PIDtoolbox@noreply.github.com>
Cc: "Bernd Klein" <berndklein@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [bw1129/PIDtoolbox] Can not load log file (maybe same as #43) (#45)


 
One minor issue is the wiki is pretty dated. The basics should still apply though I suppose

**Comment by bw1129** [comment]
You could fork, make edits, then submit as issue or pull request. Not sure how best to do it. I don’t wanna open editing to public.

**Comment by mrRobot62** [comment]
No prob - will fork it.

Let‘s what the future will bring ;-)

Nice weekend

Von meinem iPad gesendet

**Comment by bw1129** [comment]
Great! Ya I was just looking and it seems you can’t do a pull request for
The wiki, so it wouldn’t track your contributions. It may turn out to be best to just drop a Link in my wiki to your forked wiki, maybe, or I could just add it to Ptb and credit you in the wiki if you’re ok with that.

**Comment by mrRobot62** [comment]
Hi Brian,

yeah, will start with translation next days - and if I have a „first release“ you can share the link as supposed

Nice weekend (here in North-Germany bad weather to fly :-( - rain since a couple of day)

Bernd


www.myyl.com/balance

**Comment by mrRobot62** [comment]
BTW:

I don’t want to  translate 1:1 because (because that’s easy and in my opinion not my goal) I think, sometimes it’s a little better to explain the sense behind the english text - supported by some additional explanations - ok for you?

Not everyone has an expert level on tuning ;-)

Bernd


www.myyl.com/balance

**Comment by bw1129** [comment]
Sounds good.
We should continue communication another way. Can you look me up on the BB Facebook group? I’m Brian White.

**Comment by mrRobot62** [comment]
Hi ho Brian,

will search you on FB :-)

Have a look onto : 
https://github.com/mrRobot62/PIDtoolbox/blob/master/README.md <https://github.com/mrRobot62/PIDtoolbox/blob/master/README.md>

First edition (currently nothing more :-O ) -maybe with a couple of typos :-/ 


Viele Grüße
Bernd

www.myyl.com/balance







> Am 04.07.2020 um 12:47 schrieb Brian White <notifications@github.com>:
> 
> Brian White.
