### ISSUE TITLE
Couldn't install latest version-Mac 10.13.6 

### ISSUE THREAD

**Issue by Droniac75** [bw1129/PIDtoolbox#47]
I couldn't install the latest version.  The MyAppInstaller_web would crash every time.

**Comment by bw1129** [comment]
If you have a previous version, you don’t need to use the installer. Just replace the Ptb app/exe

**Comment by Droniac75** [comment]
I finally got v0.38 MyAppinstaller_web to install.  Go the same error as orlovskiy in issue 17.  Finished the install.  Double click on the PIDtoolbox icon to run app, now I get this error dbx: 

Cannot locate a valid install area 
applauncher cannot locate a valid install area.  If a MATLAB Runtime is not in the default location, then you must establish a valid install area by using system preferences panel.

**Comment by bw1129** [comment]
Check to see if contents are in the apps folder. Otherwise make sure you have it installed where you have admin rights. I’ve left similar issues up there because they show solutions so also look at those

**Comment by Droniac75** [comment]
![screenshot](https://user-images.githubusercontent.com/28690697/86544820-2a5b1300-bef8-11ea-857d-74d3319e2899.png)

**Comment by bw1129** [comment]
Not Matlab runtime. You should have a separate folder for PIDtoolbox.

**Comment by bw1129** [comment]
oh, sorry I see the Ptb folder as well. Looks like you placed it there though. I just install it from the desktop and it automatically created a PIDtoolbox folder there. But you should be able to place logfiles in any normal folder from your desktop, as long as BB decode is in there. Something is up with the way you installed that.

**Comment by mrRobot62** [comment]
Hi @Droniac75 I'm a Mac-User too, is your problem solved yet?

**Comment by Droniac75** [comment]
@mrRobot62 unfortunately, no

**Comment by mrRobot62** [comment]
ok, hope I'm able to help you. I assume u installed PIDToolbox out of the box from package and you have 
a) PIDToolbox-App installed in /Application folder 
b) a folder on your hard disk names like PIDToolbox0.391 (or something else)
c) u have installed MATLab runtime v95

As I understand your screenshot, this folder is stored under /application - right?

Ok, you can try following steps:

a) move folder out from /application to an other place on your hard disk
b) remove in /Application all PIDToolbox apps (if available)
c) out from copied PIDToolbox folder copy ONLY the PIDToolbox application into /Application
d) open a terminal and go to your PIDToolboxfolder
e) run the shell script run_PIDToobox.sh 

Does Ptb starts now? Please note: on MAC there is NO splash screen. On my MacBook Pro start takes approx 45secs (be patience ;-) 

If not, please copy & paste the log output in this thread (output from script)

if it works with the shell script close Ptb, than try the same with double click of Ptb out of /Applications

Hope this approach is more ore less clear written :-)

good luck

**Comment by mrRobot62** [comment]
don't ask - i do not know why it is posted in bold :-O

**Comment by bw1129** [comment]
it's too bad it's so complicated for the occasional mac user. the thing is, most dont have this issue, so I can't help but think it's realted to the manner in which it is being installed. All I do is drop the main and install folders on the desktop and double click the installer. is there something unique about how one is installing that is related to this failure I wonder?
