### ISSUE TITLE
Step response tool just can show case A's roll and pitch

### ISSUE THREAD

**Issue by gjjab** [bw1129/PIDtoolbox#48]
Step response tool just can show case A's roll and pitch.
Version info: betaflight 4.2, windows10.
![image](https://user-images.githubusercontent.com/6447620/87065552-c2803180-c243-11ea-81d7-52effe0153a3.png)

**Comment by mrRobot62** [comment]
could you please attach your log file

**Comment by gjjab** [comment]
THX
I am
