### ISSUE TITLE
The readme did not mention PIDtoolbox also requires Curve Fitting Toolbox

### ISSUE THREAD

**Issue by DusKing1** [bw1129/PIDtoolbox#5]
For the first time I run PIDtoolbox.m in matlab, it back a error says I need Curve Fitting Toolbox. 
I think you'd better mention that. 😃

**Comment by bw1129** [comment]
Thanks. I’ll make note of that. You could run standalone version for now. Also make sure you’re running latest version (currently 0.12). I will figure out what it needs there and try to make a workaround.

**Comment by DusKing1** [comment]
That's not a problem actually. I can restart my setup program and install Curve Fitting Toolbox.

**Comment by bw1129** [comment]
I've updated the readme in response to this. Required toolboxes: control toolbox, signal processing toolbox, image processing toolbox and statistics toolbox.

**Comment by DusKing1** [comment]
Much appreciate! 😃
