### ISSUE TITLE
Unable to open blackblox log in PIDToolbox on MAC OSX

### ISSUE THREAD

**Issue by c0debreaker** [bw1129/PIDtoolbox#52]
First, I exported the blackbox log to csv. However, in `PIDToolbox - Log Viewer`, it is not able to open the csv file. The csv file is greyed out and I can't select it.

So I tried opening the blackbox log directly. After I clicked `Load+Run` button, it failed with the following errors

<img width="415" alt="Screen Shot 2021-01-29 at 8 29 16 PM" src="https://user-images.githubusercontent.com/3783931/106344738-38e09180-6271-11eb-8745-2c01bd1d428e.png">

<img width="345" alt="Screen Shot 2021-01-29 at 8 29 26 PM" src="https://user-images.githubusercontent.com/3783931/106344742-3d0caf00-6271-11eb-9781-2c279a3a0892.png">

<img width="347" alt="Screen Shot 2021-01-29 at 8 29 42 PM" src="https://user-images.githubusercontent.com/3783931/106344744-40079f80-6271-11eb-9d7f-ad34a7e1773c.png">

I'm not sure what I'm doing wrong. What's also weird is that it's saying `.exe` which is a Windows thing.

Any help would be greatly appreciated.

**Comment by c0debreaker** [comment]
I also tried renaming the .csv file to .txt and retried the same process. I got the same errors like above.

**Comment by c0debreaker** [comment]
I now tried it on Linux. I got this

<img width="1277" alt="Screen Shot 2021-01-30 at 12 30 31 AM" src="https://user-images.githubusercontent.com/3783931/106349974-01d1a680-6298-11eb-93e5-0227d686dbcf.png">
<img width="1276" alt="Screen Shot 2021-01-30 at 12 30 47 AM" src="https://user-images.githubusercontent.com/3783931/106349979-072ef100-6298-11eb-8e79-7123f8ecbb4c.png">

I waited for 1.5 hrs and import progress bar is still like this
<img width="417" alt="Screen Shot 2021-01-30 at 1 10 03 AM" src="https://user-images.githubusercontent.com/3783931/106349985-19a92a80-6298-11eb-8ef4-448430f6e830.png">

Am I doing something wrong? I can read my blackbox log successfully using Blackbox Explorer.

Unfortunately, I don't have a Windoze machine.

**Comment by bw1129** [comment]
PTB does not support opening csv files anymore. Just use the original .bbl file and make sure you put the file in the same folder as the blacbox_decode program file. It’s all in the wiki. Follow it closely. Best to follow the blackbox log Facebook group as well. UAVtech’s blackbox site
