### ISSUE TITLE
Spectrum Analyzer Overlapping Header Info

### ISSUE THREAD

**Issue by FritzWlan** [bw1129/PIDtoolbox#53]
Great work on 0.4 - I have an issue with overlapping content on the spectrum analyzer tab. 
![overlaps](https://user-images.githubusercontent.com/64406876/121216771-80130a80-c881-11eb-9a7f-1373c60c29b5.PNG)

I am sure it is a quick fix for you! Keep up the great work.

**Comment by bw1129** [comment]
Thanks. Yes I see I’m trying to squeeze in too much there. It’s got to do with the auto font size it calculates. I’ll default that to be smaller in next version.
