### ISSUE TITLE
Error in PTload

### ISSUE THREAD

**Issue by nishanthe1** [bw1129/PIDtoolbox#59]
![error](https://user-images.githubusercontent.com/87489796/125817057-44a983a5-ca49-4212-bd9c-9f765328387b.PNG)

When i try to put a BB log it shows that message.

**Comment by bw1129** [comment]
link to logfile please. also take a look at responses to similar issue posted by others

**Comment by nishanthe1** [comment]
Hi, 

Sorry I am new to this, but it says this type of file is not supported. 
![1](https://user-images.githubusercontent.com/87489796/125831863-8d66a166-99d9-4d2e-981d-20f0fd3fe34c.PNG)

And I had a look at other threads but I couldn't find any similar issues.

**Comment by nishanthe1** [comment]
[btfl_002.zip](https://github.com/bw1129/PIDtoolbox/files/6825171/btfl_002.zip)
Here you go, sorry i managed to get it to work.

**Comment by bw1129** [comment]
Great! Be great if you could post here what you did. Valuable for others

**Comment by nishanthe1** [comment]
The blackbox Log was corrupted so therefore it was not reading the log correctly.
