### ISSUE TITLE
0.44 Spectral Analyzer not working.

### ISSUE THREAD

**Issue by FritzWlan** [bw1129/PIDtoolbox#60]
Win10Pro, PIDToolbox 0.43 worked fine. Erased 0.43 and unzipped 0.44. Stepresonse works fine. Spectral Analyzer just gives me a windows chime (error sound) and nothing happens. Maybe you can look into that, Thanks!

**Comment by bw1129** [comment]
I just tried it on my windows machine and it worked fine. I recompiled and uploaded again. Could you try downloading the win version again and giving it a try?

**Comment by drjing** [comment]
Hi, I have the same problem as well, upgraded from 0.42 and running windows 10 pro. I am installing using the web installer. I will try just copy the main files over and see if it works, report back later.

**Comment by drjing** [comment]
I have solved the windows chime by just copy all files from the main folder to the installed location.
