### ISSUE TITLE
Version 0.44 - StepResponse - several clicks on RUN create new entries in graphs

### ISSUE THREAD

**Issue by mrRobot62** [bw1129/PIDtoolbox#62]
maybe it's a bug. 

Load two files and run a step response analysis
click run
Graph is build - for both files - ok
P,I,D,Dm,F list two entries
peak - graph two points
latency - two points
click run a again
graph with two new colors
P,I,D,Dm,F list four entries
peak - graph four points
latency - four points
click run a again
graph with two new colors
P,I,D,Dm,F list six entries
peak - graph SIX points
latency - FOUR points
a.s.o

Bug is repeatable

**Comment by bw1129** [comment]
Not a bug. It’s designed to keep adding plots. If you select same files to plot each time it just keeps adding same data only with different colours

**Comment by mrRobot62** [comment]
ah - ok - make sense, I know the feature but I thought if nothing changed inside file list nothing happens if user click on RUN

but it's not a problem :-) - thanks for this quick response
