### ISSUE TITLE
Rate tuning

### ISSUE THREAD

**Issue by pulquero** [bw1129/PIDtoolbox#66]
Feature request to make it possible to evaluate rates. Given PIDtoolbox has good support for A/B comparisons, it would be nice if there was some output of % of stick range used for each axis. Maybe histogram of time spent at various stick deflections. You could then fly a track, look at the stick deflection results and adjust your expo, etc to make better use of the sticks. Additionally, a stick deflection spectrum might help detect excessive pilot overcorrection.

**Comment by bw1129** [comment]
Absolutely! There was a “flight stats tool” that I’d like to bring back with the new organization. It’s coming
