### ISSUE TITLE
Add ability to import multiple logs in one go from one BBL file

### ISSUE THREAD

**Issue by sohamsp14** [bw1129/PIDtoolbox#67]
My USB port is inaccessible on my quad. So have set up a USB2UART interface externally. This means that I can only save the log using the deprecated method. This always saves a single BBL file. When trying to add this to PidToolbox, I have to open the same file multiple times and select one log at a time. Please add the ability to add multiple logs in one go form 1 BBL

**Comment by bw1129** [comment]
It’s on the check list
