### ISSUE TITLE
v0.44: Spectral Analyzer Window doesn't open

### ISSUE THREAD

**Issue by hberg539** [bw1129/PIDtoolbox#68]
Hi,

i'm using Windows and the v0.42 worked without issues. With the new v0.44, i am having issues opening the Spectral Analyzer window with the same log files.
When i click on it, i just get the windows "alert sound", like a message window opens (but none does):
![grafik](https://user-images.githubusercontent.com/902223/132518872-5d684b64-374e-4e9c-8e61-a60d0ab419aa.png)

Here is the log file i use:
[btfl_001.zip](https://github.com/bw1129/PIDtoolbox/files/7129165/btfl_001.zip)

I'm using the betaflight 4.2.

**Comment by bw1129** [comment]
Try downloading it again. There was a fix and re upload so you might just have the older version with the bug

**Comment by hberg539** [comment]
Now it works.
Thank you for the great tool!
