### ISSUE TITLE
Invalid file identifier error

### ISSUE THREAD

**Issue by Zuldan** [bw1129/PIDtoolbox#74]
I'm trying to open a set of logs using PIDtoolbox v0.5, however I receive the following error. The logs are from Betaflight 4.3 RC2. Not sure what the issue could be. 

![Error](https://user-images.githubusercontent.com/12680150/149067369-ed8e4e9b-a8eb-4a9f-ae62-d124174e11d4.PNG)

[Logs.zip](https://github.com/bw1129/PIDtoolbox/files/7851836/Logs.zip)

**Comment by bw1129** [comment]
Have you confirmed blackbox_decode is in the folder, and that there are no spaces in the logfile name?

**Comment by Zuldan** [comment]
There are no spaces in the filenames. Whats interesting is I can load each log individually. I only get the error when I select all of them at once and load.

**Comment by bw1129** [comment]
Ah, one of them is < 1sec long or even less. That happens when you quickly arm then disarm and create a file that actually has no data. See if you select a bunch but leave out the ones < 2sec (control plus mouse or apple then mouse in mac I think and you select multiple individual files)

**Comment by Zuldan** [comment]
Thanks for the explanation Brian. Appreciate your help.
