### ISSUE TITLE
0.5.2: Unable to set user defaults

### ISSUE THREAD

**Issue by L1cardo** [bw1129/PIDtoolbox#78]
You said in the Youtube video that I need to put mainDir.txt file in root directory of my mac which is “Macintosh HD”, and this is a Read-only directory, I can't place any file here.

<img width="192" alt="image" src="https://user-images.githubusercontent.com/33802186/159619451-1838bdda-7684-4fbd-8f6b-1a905024d3e9.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/33802186/159621588-635aac4e-ad86-4569-b90a-3f98bf805f82.png">

Directory: /Desktop
Mac: Mac mini M1
OS: macOS 12.3 (21E230)
Version: PTB 0.5.2

**Comment by bw1129** [comment]
I have found a workaround for this issue. Please grab it again, as I have made a small change. Follow the steps in the 'README' file.

**Comment by L1cardo** [comment]
Yeah, this worked now.
Another question, can I delete mainDir.txt file after everything is done?

**Comment by mituritsyn** [comment]
@bw1129 @L1cardo 

could we close this issue?

**Comment by bw1129** [comment]
Pls watch the video
https://youtu.be/oH-vN1A5Hfc
