### ISSUE TITLE
0.55: UI not properly on Monterey

### ISSUE THREAD

**Issue by Joerg-H-Wagner** [bw1129/PIDtoolbox#81]
The selection list shows a white line of the active entry.
Collapsed it's blended together.
Mojave is okay.
<img width="170" alt="Bildschirmfoto 2022-05-03 um 22 09 08" src="https://user-images.githubusercontent.com/93326228/166558193-e019f734-1aeb-4b89-a876-344baa01d93a.png">
<img width="168" alt="Bildschirmfoto 2022-05-03 um 22 09 23" src="https://user-images.githubusercontent.com/93326228/166558198-f6ca732f-bd55-4baa-aaa3-85a11959b047.png">

**Comment by Hawxxer** [comment]
+1 also I can't open step response
