### ISSUE TITLE
MatLab installation fails on Windows 11 - Error finding installer class 

### ISSUE THREAD

**Issue by Sol1du2** [bw1129/PIDtoolbox#82]
I am having some trouble installing MatLab via the provided installer, on Windows 11.

I tried moving the installer to a shorter and simpler path as suggested after googling the error (some users point to the possibility of the error being due to non ascii characters in the path) but to no avail. A screenshot of the error is below. It pops up pretty much immediately after starting the installer.

<img width="209" alt="matlab error" src="https://user-images.githubusercontent.com/8356992/167844225-80461e6f-82aa-4a23-8faf-3397c77f57f8.png">

**Comment by Sol1du2** [comment]
Nevermind it seems the issue is indeed non ascii characters but in the user folder, not specifically where the installer is. Changing my username folder to only ascii characters resolved the issue.

This might also not be exclusive to win11

**Comment by bw1129** [comment]
How long ago did you grab v0.55? That issue was fixed recently and just re-uploaded to 0.55

**Comment by Sol1du2** [comment]
> How long ago did you grab v0.55? That issue was fixed recently and just re-uploaded to 0.55

A few minutes before my original post. 

Hm, unfortunately after installing I can not start it. The splash screen comes up and then it just closes

**Comment by bw1129** [comment]
Read the ‘README_PLEASE.txt’ very carefully

**Comment by Sol1du2** [comment]
I did but I'm still failing to see why it doesn't start 😆

**Comment by bw1129** [comment]
Find me on Facebook messenger and I’ll talk you through it
