### ISSUE TITLE
Error in PTload MacOS 

### ISSUE THREAD

**Issue by mtshare** [bw1129/PIDtoolbox#87]
Hi guys,

I'm trying to analyze my LOG from my quads but on both my Mac (iMac i7 & MacBook Pro M1) I'm getting this error (see attached image).
Can you help me figure out what's wrong?
This log works fine on Blackbox Explorer.

Attached you can find the ZIP with my BFL log.

**My Blackbox Log settings are:**
_Blackbox logging rate:_ 1/2 (4Hz)
_Blackbox debug mode:_ GYRO SCALED
I'm on **Betaflight 4.3** (latest stable release)

Thank you so much.

![PidToolbox Error](https://user-images.githubusercontent.com/387165/174885807-e50e6b7b-180f-4da6-9c53-ef342fa010d2.png)
[LOG00003.BFL.zip](https://github.com/bw1129/PIDtoolbox/files/8952371/LOG00003.BFL.zip)

**Comment by bw1129** [comment]
no issues on my end. notice your table bottom right. You have not set things up correctly. Follow the 'README_PLEASE.txt.' file
![PTB_FIGS_21-Jun-2022-1](https://user-images.githubusercontent.com/17284912/174911295-7138cacb-7f0c-4023-b9a0-d84c19d588a8.png)

**Comment by bw1129** [comment]
Do NOT put logfiles in the main folder for v0.55

**Comment by bw1129** [comment]
your first mistake is running the application from the apps folder. I stated not to do that.

**Comment by mtshare** [comment]
Thank you for the support and sorry to bother you.
I really followed all the steps of the README file:

1. drop this 'main' folder and all of it's contents onto your desktop **DONE √**
2. Run the 'PIDtoolbox.app' program file directly from that 'main' **DONE √**

I still get this error:
[https://drive.google.com/file/d/13_3sg9wFGlNaX1BLYobryPA_mAtKRpCD/view?usp=sharing](url)

But it doesn't metter, my workatround is to put a copy of the log in the main folder and it works.

**Comment by bw1129** [comment]
join zoom chat and I'll fix it up. https://queensu.zoom.us/j/95721856459?pwd=UUtiSTRUQUxBck5RSFMxcGwzOGZQQT09
