### ISSUE TITLE
Does not run. Only splash image shown

### ISSUE THREAD

**Issue by Cleric-K** [bw1129/PIDtoolbox#9]
Hi,
I've just installed manually the `9.3` matlab runtime.
Running `PIDToolbox.exe` displays the splash image and then the process silently ends.
I don't see any logging in the Windows logs. Is there a way to run in console mode with logging?

**Comment by Cleric-K** [comment]
I see that the matlab compiler can generate console version of the `.exe`. Can we do that? That should give some clue what's happening.

**Comment by bw1129** [comment]
Try using the provided installer rather than downloading manually.

**Comment by Cleric-K** [comment]
I tried that but the behavior is the same. So all cases are:
* manually installed runtime and running directly from `main` directory.
* manually installed runtime and using your installer. It detects that the runtime is already installed and uses it.
* no pre-installed runtime and using your installer. It downloads and installs the runtime.

In all cases the behavior is the same: The splash image appears and then the process ends.

We need to get some logging.

**Comment by bw1129** [comment]
it can be stubborn. I dont understand the intricacies of runtime, but I think you have to remove/uninstall the previous, then for good measure, restart your computer, then do a complete new reinstall from the provided installer. I just put the entire folder on the desktop, and install from there, but I dont think it matters. try that and let me know how it goes.

**Comment by Cleric-K** [comment]
I tried now, but it's the same.

Is it possible to generate console version of the `exe`?
Do you use the `mcc` compiler? It should be possible to generate console version with `-m` argument instead of `-e` (which generates Windows native app).
https://www.mathworks.com/help/compiler/mcc.html

**Comment by bw1129** [comment]
that's really unfortunate man. 
no I dont know how to generate a console version. I use the build-in app compiler gui. there are no options you're mentioning. I can look into it.

**Comment by Cleric-K** [comment]
I'm trying now at my office PC (Desktop Win10 64).
Will try later at other PCs - I assume it will work there, so it's no that of a problem, but it's just curious what could be the reason. Should be something quite specific to the current configuration (although it's pretty standard PC).

**Comment by bw1129** [comment]
I think windows is holding something from the manual install that's not letting you past. there are now many people using it with no issues so that makes it a tricky thing to solve. Im sure it has something to do with paths, but Im not an expert in dealing with this. and the real trick is I can never know how its going to work on everyone's computer. I hope it works on your other windows machine

**Comment by Cleric-K** [comment]
Can you tell me what version of MATLAB are you using? Is this capability of producing compiled version inbuilt or a separate product?
I'll see if I can get a MATLAB installation and compile myself.

**Comment by bw1129** [comment]
Im on 2017b, but you'll need a bunch of toolboxes to run it. you need those toolboxes to compile too I think. Well, you'll for sure need compile-related toolboxes. But if you have matlab, then you can just run pidtoolbox from there. It's way faster if you just run from matlab command prompt.

**Comment by bw1129** [comment]
let me know if it worked on your other machine??

**Comment by Cleric-K** [comment]
I tried it on a VirtualBox on the same machine that has the problem and it works there.
It's clear that there's something with this setup that breaks it, but it's not possible to tell without some kind of logging.

When possible I'll try compile myself the exe.

**Comment by watageek** [comment]
I had issue on two computer. Splash screen close then nothing appear. 

I5 650
Win7

AMD c50
Win10

On both I disabled real time antivirus, and I started flawlessly.

Both are running MSessential antivirus/window antivirus

**Comment by Cleric-K** [comment]
Interesting. I'll try that, but probably next week I'll have access to the problematic pc.

**Comment by ReefsnRidges** [comment]
Having the very same problem with windows 10.  Tried disabling antivirus, uninstall and re-install, reboot and all I get is the splash screen?  I also did  install the runtime file.

**Comment by watageek** [comment]
The most possible issue is more than one instance of antivirus running or more than one program.

If you see the splash screen it is most likely you need disable real time protection.

If it is running on a 9watt cpu, anything can run it.

Open the task manager and see if find the culprit

**Comment by ReefsnRidges** [comment]
Thank you for the suggestions, very much appreciated as I so badly want to use this tool however, same result.  From the task manager I could not see anything active when trying to launch toolbox.  Cleared the history and tried too, nothing except the error msg ".  At a loss...

**Comment by bw1129** [comment]
@ReefsnRidges
Did you use the installation file to install the entire program? Do you get an error message or just hanging on splash screen on startup?

**Comment by ReefsnRidges** [comment]
Yes, used the install file for everything.  Two days ago it decided to work.  Today again, same story.  No error message other than a chime from windows 10 when it try's to open and if I watch the task manager, it only pops up briefly when the splash screen is closing and indicates a "program not responding".

**Comment by ReefsnRidges** [comment]
Brian, don't want to jinx myself here but wanted you to know I have it working.  Cleaned my registry thinking maybe left over files from to many install/un-installs and it worked immediately.  Thank you for all you do including trying to get me going here, much appreciated!  You guys are so giving of your time and expertise and I feel like you don't get near enough credit for what you do.  THANK YOU!!!

**Comment by Cleric-K** [comment]
@ReefsnRidges Can you specify what registry entries you have deleted? I want to try it with a machine that has the same problem.

**Comment by bw1129** [comment]
@ReefsnRidges Thanks very much man! greatly appreciated. I'm glad to figured out the issue. I will keep this thread open so others can see a potential solution if they have a similar issue.

**Comment by ReefsnRidges** [comment]
The problem started when I tried to move the files (Pidtoolbox) into another directory as it worked prior to this move.  I then did countless install/unistall trying to get this to work, which further exasperated the problem.  I can't tell you specifically what files.  I can tell you what tipped me off was when doing an uninstall, I got a message that all related files were not uninstalled from the registry, and that I'd have to do that manually.  I have the free version of "CCleaner" so ran the registry cleaner which deletes files not associated with anything (after making a back-up of those files of course via the program).  After a scan I noticed in the files to be deleted there were several files from "Pidtoolbox" and once deleted, the Pidtoolbox came to life. Hoping this does the same for you as it is a great tool to have.  Best of luck!

**Comment by ReefsnRidges** [comment]
Update: Not working again today.  Thanks everyone for your help.  Just to unreliable and time consuming at this point for me to continue, the white flags going up.

**Comment by bw1129** [comment]
@ReefsnRidges is it always an issue of the program not starting, or are you mixing in issues with hanging while loading log file? Also remind me is this Mac or Windows?

**Comment by ReefsnRidges** [comment]
Program not starting on Windows 10 PC. Splash screen pops up, Windows chime sounds and splash disappears. Within task manager it pops up as PIDtoolbox and a message “program not responding.

**Comment by lylus** [comment]
win10 64bit 遇到了同样的问题。望能解决。

**Comment by UglyBabyGaming** [comment]
Hi I had this working no problem at the weekend.. few days later just shows splash and shuts off
tried re-install no joy

**Comment by bw1129** [comment]
I think windows updates are blocking it. Go to folder where the executable is and make sure it had full read write access

**Comment by UglyBabyGaming** [comment]
No joy even run as administrator (did full premisionin the propertys tab under security)

**Comment by bw1129** [comment]
I suspect latest windows isn’t playing well will 2017 Matlab runtime. I may begin compiling with latest Matlab.

**Comment by UglyBabyGaming** [comment]
Using Windows 10 it happened before on an older version last year as well.
Hope you get it fixed its easy to use when working thanks.

**Comment by bw1129** [comment]
Unfortunately it’s not me. There’s nothing in PTB code related to that. It’s a ML runtime windows issue. Some fix it by reinstalling

**Comment by Guidus93** [comment]
I have the same issue.
I reinstalled the runtime, try to download from Matlab website also and can't fix. I only get the splash screen. 
I also cleaned the register. 
I have Matlab 2021b installed and works if i execute the script from matlab direclty.

**Comment by UglyBabyGaming** [comment]
I will try it out I was asking on the TBS lounge someone said it stopped and just started working again later for no reason??? This tool is so useful for tuning Ya Genus just all need the reliability of it working looking forward to the updated version.. ps basement tune soooo locked in on test flight. can you do a vid on tuning Dmax Bf 4.3? as only tuned Dmin and left Dmax off… the tune is so good I actually dropped my rates by 180deg/sec
