### ISSUE TITLE
Can't open logfile

### ISSUE THREAD

**Issue by tjseydel** [bw1129/PIDtoolbox#90]
Hello,

First of all, thank you for all the hard work you have put in. 
I had never used PT before and had a hard time opening log files. I followed the readme to letter, but nothing seemed to work.
Then it hit me. I had an "&" in my log file title. Something along the lines of "P&I1.0.bbl".
Apparently, this isn't handled well by the program. Not sure if this is something that can be fixed, but leaving this here just in case someone finds themselves in the same situation.

**Comment by bw1129** [comment]
Yea no weird characters. Standard ascii I presume.
