### ISSUE TITLE
Trying to install PTB in windows 10 but not working

### ISSUE THREAD

**Issue by rokfpv** [bw1129/PIDtoolbox#94]
I installed the PTB latest version in Desktop foler and Matlab automatically installed in program folder.
Afterward, I running the PTB in main folder but it won't open it just showing the PTB image quickly and gone.
Any errors coming

I did couple of times to remove PTB and reinstall it. Still it is not working properly.

**Comment by DenchiG13** [comment]
I have the same problem

**Comment by FlopBuster** [comment]
any solutions?

**Comment by treadwm** [comment]
Same issue here.

**Comment by FlopBuster** [comment]
solved by cleaning the %TEMP% folder.

**Comment by treadwm** [comment]
Having similar issue on Win10. Cleaning the %TEMP% folder did not help. Uninstalled everything, rebooted, ran installer script, extracted files to folder on desktop and ran exe out of main. I see splash screen and it stops. No other obvious errors. All folders involved are lower case with no odd characters.

**Comment by treadwm** [comment]
@NoSelph Unfortunately uninstall/reinstall didn't work for me. To be clear, this is on a laptop with a relatively new Win10 install. The only other things installed on it is prusa slicer and Betaflight configurator. It's only ever had the 0.59 version of PTB attempted to be installed. This same install procedure worked w/o issue on another pc of mine so I'm a bit confused.

**Comment by delagra** [comment]
Same issue, installed, ran the PIDtoolbox.exe from main folder, splash screen loads and that's it. Cleaned up temp folder, uninstalled and reinstalled runtime, restarted the computer, tried various compatibility options, nothing helps.
