### ISSUE TITLE
can't show help window

### ISSUE THREAD

**Issue by aiyYu** [bw1129/PIDtoolbox#98]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/49424498/212347025-9d5f1330-9e77-44fa-afea-e7540b29b5f5.png">

0.59
os:mac Ventura

**Comment by tonvfx** [comment]
Seeing the same issue. MacOs Ventura 13.1. It's there but invisible.

**Comment by fabianphilipp** [comment]
Same issue here. Mac Ventura 13.1. Can't see the help window.
![image](https://user-images.githubusercontent.com/123021783/213285613-05dfbd1b-d85c-4bb0-aad2-ed5f119d6c03.png)
