### ISSUE TITLE
MAC os m2 sos

### ISSUE THREAD

**Issue by DAJone** [bw1129/PIDtoolbox#99]
I cannot run pidtoolbox under the system of MacOS 13.1. My processor is m2, and the environment has been properly configured. Open pidtoolbox to show that it is running, but there is no response. I cannot open the software

**Comment by DAJone** [comment]
However, I can open pidtoolbox 0.57 and below, but I can't run it. There is no response after loading the bbl file. I am eager to get a reply

**Comment by renatux** [comment]
Please, see this:
https://github.com/bw1129/PIDtoolbox/issues/93

**Comment by cdshepster** [comment]
Temporary Fix until next release:
https://github.com/bw1129/PIDtoolbox/issues/93#issuecomment-1434289467
